### ISSUE TITLE
I am supplying a value but ssh-deploy says I'm not.  Any thoughts please?

### ISSUE THREAD

**Issue by DeeLindesay** [ForbesLindesay/ssh-deploy#1]
```
C:\Users\Dee\Documents\GitHub\MAPS [master]> ssh-deploy env-set london --name MAPS_CURRENCY_FORMAT --value "-£9,###,###,###,##0.00"
C:\Users\Dee\AppData\Roaming\npm\node_modules\ssh-deploy\node_modules\promise\node_modules\asap\asap.js:45
                throw e;
                      ^
Error: You mut provide a value for value
    at C:\Users\Dee\AppData\Roaming\npm\node_modules\ssh-deploy\index.js:28:17
    at Array.forEach (native)
    at C:\Users\Dee\AppData\Roaming\npm\node_modules\ssh-deploy\index.js:26:18
    at C:\Users\Dee\AppData\Roaming\npm\node_modules\ssh-deploy\node_modules\promise\core.js:33:15
    at flush (C:\Users\Dee\AppData\Roaming\npm\node_modules\ssh-deploy\node_modules\promise\node_modules\asap\asap.js:27
:13)
    at process._tickCallback (node.js:355:11)
```

**Comment by DeeLindesay** [comment]
PS tried it without the negative sign and got
```
C:\Users\Dee\Documents\GitHub\MAPS [master]> ssh-deploy set-env london --name MAPS_CURRENCY_FORMAT --value "£9,###,###,###,##0.00"
C:\Users\Dee\AppData\Roaming\npm\node_modules\ssh-deploy\bin\cli.js:81
  deploy[argv._[0]](argv._[1], argv).done();
                   ^
TypeError: undefined is not a function
    at Object.<anonymous> (C:\Users\Dee\AppData\Roaming\npm\node_modules\ssh-deploy\bin\cli.js:81:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by DeeLindesay** [comment]
It has, however worked without the negative symbol in the format string
